apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rapidocine-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - rapidocine.example.com
      secretName: rapidocine-tls
  rules:
    - host: rapidocine.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rapidocine-app
                port:
                  number: 80
