apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rapidocine-ingress
spec:
  rules:
    - host: rapidocine-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rapidocine-app
                port:
                  number: 80
