apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rapidocine-dev

# Base configuration
bases:
  - ../../base

# Development-specific patches
patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

# Development ConfigMap
configMapGenerator:
  - name: rapidocine-config
    behavior: merge
    literals:
      - DEBUG=True

# Development replicas
replicas:
  - name: rapidocine-app
    count: 1

# Development images
images:
  - name: rapidocine
    newName: rapidocine
    newTag: dev

commonLabels:
  environment: development
